### PR TITLE
Bumps minimum version to PHP 7.2 and adds support for PHP 8.0

### PR DESCRIPTION
**Pull request by bencorlett**

### CODE REVIEW

**Comment by mattkingshott** [comment]
This is great news for PHP 8! 

Are you expecting to publish a new release soon?

Thanks!

**Comment by bencorlett** [comment]
@mattkingshott thanks :). Yep, I have this MR (against the unreleased V2) plus another targeting V1. Plan to release 1.9.0 within a day or so and V2 when I can complete documenting it.

**Comment by mattkingshott** [comment]
Great. Thanks!

**Comment by mattkingshott** [comment]
Hi @bencorlett any update on releasing v1.9.0? Thanks!

**Pull request merged**
