### PR TITLE
[2.0] Use RandomLib to generate a secure nonce

### PR DESCRIPTION
**Pull request by shadowhand**
The current method is not cryptographically secure.

https://paragonie.com/blog/2015/07/how-safely-generate-random-strings-and-integers-in-php

### CODE REVIEW

**Comment by stevenmaguire** [comment]
:+1:

**Comment by paragonie-scott** [comment]
:+1:

**Comment by shadowhand** [comment]
@paragonie-scott that wouldn't work, the `nonce` method is `static`.

**Comment by stevenmaguire** [comment]
youre my hero

**Pull request merged**
