### PR TITLE
Magento: User info endpoint added

### PR DESCRIPTION
**Pull request by vovayatsyuk**
This allows to get authenticated user info

### CODE REVIEW

**Comment by vovayatsyuk** [comment]
If somebody is interested about Magento's `/api/rest/customers` userinfo endpoing returing values, you can check [_getCollectionForRetrieve](https://github.com/speedupmate/Magento-CE-Mirror/blob/master/app/code/core/Mage/Customer/Model/Api2/Customer/Rest/Customer/V1.php#L69-L72) method.

**Comment by vovayatsyuk** [comment]
Sorry for disturbing you again, but is it ok to wait for a response for 2 weeks?

**Comment by bencorlett** [comment]
Hi,

I've been away lately and due to the nature of needing to setup a Magento environment to test this, it's not trivial to evaluate. 

I will look at this ASAP this week (I'll try today).

**Comment by vovayatsyuk** [comment]
Thanks.

In case if you need an instructions on how to setup magento for a userdata endpoint, you can 
take a look into my instructions: https://github.com/vovayatsyuk/flarum-ext-auth-magento#magento-setup

**Pull request merged**
