### PR TITLE
Populate missing user fields in BitBucket provider

### PR DESCRIPTION
**Pull request by aztech-dev**
Title speaks for itself

### CODE REVIEW

**Comment by bencorlett** [comment]
Are those fields alway present in every request? (i.e., can the user can configure their account not to expose those fields?)

**Comment by bencorlett** [comment]
Thanks for the PR by the way :)

Just undertaking the due diligence required before merging in.

**Comment by aztech-dev** [comment]
You're welcome :)

From the documentation, it seems that the fields would be empty when the value is not available (ie, last_name field is empty for field accounts): https://confluence.atlassian.com/display/BITBUCKET/user+Endpoint#userEndpoint-Overview

I just checked by clearing out my user profile and it confirms that the fields are present when not set (even when the profile is set to private).

**Comment by bencorlett** [comment]
Perfect! Thanks :)

**Pull request merged**
