### PR TITLE
Fixed array normalization in baseString method that also led to an ex…

### PR DESCRIPTION
**Pull request by smares**
…ception with PHP 8.

Resolves https://github.com/thephpleague/oauth1-client/issues/127

### CODE REVIEW

**Comment by mattkingshott** [comment]
Thanks @smares. I have closed my previous pull request in favour of this one.

**Comment by smares** [comment]
The second commit was an attempt to fix tests. Not exactly sure how to fix the `--prefer-lowest` ones.

**Comment by mattkingshott** [comment]
I'm not sure that you can. It may require a version bump.

**Comment by bencorlett** [comment]
> I'm not sure that you can. It may require a version bump.

I'm currently looking into this 👍 

@smares could you please rebase your MR on top of `master` again, I noticed I did basically the same as one of your commits (the most recent one), you should be able to drop that one.

Thanks!

**Comment by bencorlett** [comment]
Thank you! 🍴 merged 🥳

**Pull request merged**
