### PR TITLE
Decouple from Guzzle

### PR DESCRIPTION
**Pull request by Nyholm**
To completely decouple from Guzzle I've used the HTTPlug abstraction. This change does not break BC.

The benefits of this is users stuck with Guzzle5 can still use this library. 

FYI: other libraries using HTTPlug are Geocoder, Mailgun, FosCache, KnpGithubApi and more.

### CODE REVIEW

**Comment by stevenmaguire** [comment]
FYI there is a [similar and related conversation](https://github.com/thephpleague/oauth2-client/pull/538) in the oauth2-client

**Comment by Nyholm** [comment]
Yes, thank you for the link. 

What do you think of this PR @stevenmaguire?

**Comment by bencorlett** [comment]
Hi @Nyholm,

Firstly, thank you very much for this PR! Wow. I love it.

I'm going to look further into the code to see if I can provide any feedback and I'll checkout the discussion that @stevenmaguire referred to.

Watch this space :)

**Comment by aferrandini** [comment]
Thanks for the PR @Nyholm
:+1: for me

**Comment by bencorlett** [comment]
Hi @Nyholm, so obviously this discussion is way stale. But I have an update.

In the [new version](https://github.com/thephpleague/oauth1-client/pull/111), we have completely decoupled from any particular HTTP implementation. We're using PSR-7, PSR-17 and PSR-18 only. We recommend the use of Guzzle, but we don't require it.

Thank you for opening this discussion years ago, it's definitely been factored in with the rewrite.

**Pull request closed without merging**
