### PR TITLE
Resolve PHP 8 warning

### PR DESCRIPTION
**Pull request by mattkingshott**
This fixes a PHP Warning generated on version 8.

### CODE REVIEW

**Review by smares — CHANGES_REQUESTED** [review]
This method makes no sense anyways.

1. The callback method's arguments are wrong, the first argument passed is the value, the second is the key. Only the first argument (the value) can be passed by reference, hence the error in the bug. There is no way to modify the key like this method intended to.
2. Even if the second argument could've been passed by reference, this fix would've rendered the `$value = ...` line useless as you're now throwing away the write-back capability.

What this should do is recursively split the array into keys values, perform the `array_walk` on the two arrays with the keys and values and then `array_combine` the processed keys and values back to one array.

**Comment by mattkingshott** [comment]
Begs the question as to why it’s in there... 🤷🏻‍♂️

**Comment by mattkingshott** [comment]
Not sure when I’ll get the chance to make the proposed changes. Any chance you can submit them @smares?

**Comment by smares** [comment]
Sure, created https://github.com/thephpleague/oauth1-client/pull/129 which ended up being different than what I proposed here, hehe.

**Comment by mattkingshott** [comment]
Closed. Review #129 for a better fix.

**Pull request closed without merging**
