### PR TITLE
Version-2 for PHP7.2+ featuring Guzzle-7

### PR DESCRIPTION
**Pull request by shehi**
An attempt to make this package PHP7.2+ compatible, featuring the latest versions of its dependencies as possible.
- Cleaned up (without any change to logic, but with minor implementation fixes) the codebase making it PHP7 and PSR0 compat.
- Updated the tests in a very minor way, to reflect return-type expectations to align with Guzzle-7 classes
- Updated Travis-CI flow: disabled Scrutinizer as it somehow doesn't work with PHP7, which can be fixed later
- Added Docker Compose setup for development purposes which features OOTB Xdebug setup (port 54321, ideKey=basisPhp). Container used is from another OS project of mine, but can be replaced later on, when something specific to this project or League gets created.
- Updated composer dependencies to the latest version (as possible).
- Dropped PHP-CodeSniffer in favor of Php-Cs-Fixer. Maybe later Psalm can be added, when typing issues are completely resolved.

Expectations from this PR:
- To have a 2.0 release with PHP7.2+ only support.

Further notes:
- Recommend to refactor existing "Version-2" branch on top of this one, for possible 3.0 release.
- Although Guzzle-7 works fine in this PR, in future, [PSR-18 implementation](https://github.com/php-fig/http-client) should be brought forward to decouple from Guzzle.
- Some online coverage service should be added as part of CI. Scrutinizer is really behind (I used it in past as well, in my other projects)

### CODE REVIEW

**Comment by shehi** [comment]
https://github.com/composer/composer/blob/28f0d8fcf7e2d6cb207b3c6ceca0e6142d141a7f/bin/composer#L22

HHVM 4.0 has dropped support for Composer

**Comment by shehi** [comment]
https://symfony.com/blog/symfony-4-end-of-hhvm-support

Symfony 4 dropped HHVM support ages ago as well. I suggest doing the same here, instead of wasting time with this package endlessly, which itself works with an old tech of Oauth-1

**Comment by shehi** [comment]
Ok, so we have PHP 7.4 incompatibility. The rest passes tests.

**Comment by mfn** [comment]
Try relaxing the mockery version constraint, seems to be source no. of the failing tests.

**Comment by shehi** [comment]
I think we have to ditch PHP 5.5 as well:
```
 Problem 1
    - mockery/mockery 1.4.2 requires php ^7.3 || ^8.0 -> your PHP version (5.5.38) does not satisfy that requirement.
    - mockery/mockery 1.4.1 requires php ^7.3 || ^8.0 -> your PHP version (5.5.38) does not satisfy that requirement.
    - mockery/mockery 1.4.0 requires php ^7.3.0 -> your PHP version (5.5.38) does not satisfy that requirement.
    - mockery/mockery 1.3.3 requires php >=5.6.0 -> your PHP version (5.5.38) does not satisfy that requirement.
    - mockery/mockery 1.3.2 requires php >=5.6.0 -> your PHP version (5.5.38) does not satisfy that requirement.
    - mockery/mockery 1.3.1 requires php >=5.6.0 -> your PHP version (5.5.38) does not satisfy that requirement.
    - mockery/mockery 1.3.0 requires php >=5.6.0 -> your PHP version (5.5.38) does not satisfy that requirement.
    - mockery/mockery 1.2.4 requires php >=5.6.0 -> your PHP version (5.5.38) does not satisfy that requirement.
    - mockery/mockery 1.2.3 requires php >=5.6.0 -> your PHP version (5.5.38) does not satisfy that requirement.
    - mockery/mockery 1.2.2 requires php >=5.6.0 -> your PHP version (5.5.38) does not satisfy that requirement.
    - mockery/mockery 1.2.1 requires php >=5.6.0 -> your PHP version (5.5.38) does not satisfy that requirement.
    - mockery/mockery 1.2.0 requires php >=5.6.0 -> your PHP version (5.5.38) does not satisfy that requirement.
    - mockery/mockery 1.1.0 requires php >=5.6.0 -> your PHP version (5.5.38) does not satisfy that requirement.
    - Installation request for mockery/mockery ^1.1 -> satisfiable by mockery/mockery[1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.4.2].
```

**Comment by mfn** [comment]
No sure, you can try `^0.9 | ^1.1` for mockery. If lucky the dependencies sort it out itself.

But OTOH, everything not receiving security fixes should probably be dropped…

**Comment by shehi** [comment]
Ok, I have a suggestion here:

Laravel/Socialite needs Guzzle-7, which is PHP-7.2+, as Laravel 7 is.

I suggest instead of wasting time with PHP 5.x, we just go PHP-7.x, first settle dependencies, then cleanup the code a bit making it more PHP-7'ish and do a major release. PHP-5 isn't really worth all this effort. Down the line I can clean up the code myself.

So far, Mockery 1.1 works fine. Even PHP 7.4 passes all the tests.

**Comment by shehi** [comment]
CC: @bencorlett

**Comment by shehi** [comment]
Took me 7-8 hours to refactor this thing. It is done now. We need someone to test it :D

**Comment by bencorlett** [comment]
> Took me 7-8 hours to refactor this thing. It is done now. We need someone to test it :D

Hey @shehi! Thank you very much for your effort. I noticed we're targeting PHP7.1+ with some of the language features (nullable return types, `void` return types etc).

I agree in dropping support for PHP 5 and making this work in PHP 7.  I will set aside time this week to review your PR in more detail and possibly provide some suggestions.

I would like to put some serious consideration into a newer version of this project that's rewritten. For that, we'd support say PHP 7.2+.

Thank you again :)

**Comment by shehi** [comment]
Hey @bencorlett !

This PR is indeed 7.2+. And it introduces absolutely nothing, just cleans the code up. One thing we need to make sure is to check whether I didn't mess up somewhere - so it needs to be tested in Live (which will be significant undertaking, considering the number of platforms this package supports - from Magento to Xing). Good luck and have fun!

**Comment by arcanedev-maroc** [comment]
Hi @shehi, great work :+1: 

I think you should target the `develop` branch instead of `master`

**Comment by shehi** [comment]
@arcanedev-maroc , @bencorlett changed base to 'develop'

**Comment by shehi** [comment]
Nope develop is old and ugly. Tons of conflicts. Delete it, recreate fresh from master and let me know. I will change the base again.

**Comment by arcanedev-maroc** [comment]
I agree with you, the `develop` branch must be a copy of the `master` branch

But don't forget to add [this line](https://github.com/thephpleague/oauth1-client/blob/develop/composer.json#L44)

**Comment by shehi** [comment]
Then the branch name should be the one mentioned in that line, not develop.

**Comment by arcanedev-maroc** [comment]
Hi @bencorlett, can you delete&create `develop` branch ? Last commit was Aug 17, 2016, it's :skull: now 

Or create a new branch, something like `2.x`

I'm willing to test the changes (with Laravel Socialite) and help if possible

**Comment by bencorlett** [comment]
I’ve spoken with other league maintainers and we are very thankful for this PR, however the scope of what it addresses is well outside of allowing a newer guzzle and php version. 

The inclusion of custom Docker images etc is not something we typically chase with league packages. 

I’m currently working on a rewrite of the  project and will update you in the coming days on that. 

Thanks! Your contributions and efforts do not go unnoticed :)

**Comment by shehi** [comment]
> I’ve spoken with other league maintainers and we are very thankful for this PR, however the scope of what it addresses is well outside of allowing a newer guzzle and php version.

With all due respect, this is a nonsense. This PR has introduced absolutely nothing, except PHP7.2+ compatibility. If you disagree, show me a line plz.

> The inclusion of custom Docker images etc is not something we typically chase with league packages. 

Again, with all due respect, this isn't even an argument to make. I added it when I worked on this package. Many devs like me don't install anything on their host machines, to be absolutely independent from maintenance of such environment. As such, I  needed an env to develop in. I didn't intend to have docker related stuff in this package. They are already removed.

> I’m currently working on a rewrite of the project and will update you in the coming days on that.

This one needs the biggest "with all due respect" :) The only reason I did all this work is because we have tons of libraries that depend on yours, and are stuck with old version of Guzzle, not being able to move forward. You guys already "have been working on a new version" literally for several years. The current urgency is the only reason I wanted this to go through.

**Comment by bencorlett** [comment]
Hi Shehi, thanks for the feedback.

I should add, my first two sentences are addressing the same concern - the inclusion of custom Docker images in a PHP library (not project, library) seem overkill for the aim to minimise dependencies. I see that, after my comment, before your comment, you've removed these. I think that's an acknowledgement that this is in fact an argument to make. That's great.

I am a big fan of all community contributions and I intend to do one of two things:

1. Use this PR as-is, or
2. Cherry pick commits out of it.

I think acknowledgement of work is important and I don't want to take your work and not keep your name on your commits. That's something which really gripes me with some open source projects.

I think the plan forward in terms of merging this PR is that I'll go through and leave some feedback, if we can address that, we should be good to go.

**Comment by bencorlett** [comment]
Hi Shehi, thanks for the feedback.

I should add, my first two sentences are addressing the same concern - the inclusion of custom Docker images in a PHP library (not project, library) seem overkill for the aim to minimise dependencies. I see that, after my comment, before your comment, you've removed these. I think that's an acknowledgement that this is in fact an argument to make. That's great.

I am a big fan of all community contributions and I intend to do one of two things:

Use this PR as-is, or
Cherry pick commits out of it.
I think acknowledgement of work is important and I don't want to take your work and not keep your name on your commits. That's something which really gripes me with some open source projects.

**Comment by bencorlett** [comment]
Hi Shehi, thanks for the feedback.

I should add, my first two sentences are addressing the same concern - the inclusion of custom Docker images in a PHP library (not project, library) seem overkill for the aim to minimise dependencies. I see that, after my comment, before your comment, you've removed these. I think that's an acknowledgement that this is in fact an argument to make. That's great.

I am a big fan of all community contributions and I intend to do one of two things:

1. Use this PR as-is, or
2. Cherry pick commits out of it.

I think acknowledgement of work is important and I don't want to take your work and not keep your name on your commits. That's something which really gripes me with some open source projects.

**Edit**

I want to merge your MR or cherry pick commits from it, however there's one large commit at the start that includes a bunch of changes (such as the inclusion of the `composer.lock` file) that would be hard to mix and match.

I might start another followup MR and take from this what I can and include credit wherever possible.

I think the first step is to reconcile master vs. develop, then open a PR, cherry pick what I can and tidy up. I welcome your assistance there too. I'll update you once I have the PR up in its early form.

**Comment by shehi** [comment]
> I want to merge your MR or cherry pick commits from it, however there's one large commit at the start that includes a bunch of changes (such as the inclusion of the composer.lock file) that would be hard to mix and match.

I fail to understand why would someone need to disect `composer.lock` file into pieces. It's technically parsed version of `composer.json` that accompanies it. Noone would commit `composer.lock` of unrelated `composer.json`. Additionally, whenever I commit anywhere, whether it is open-source, professional life or my own pet projects, my commits intend to be atomic (meaning all of them have to be a working instance of the code, not broken one). As such, I never have commits in between where things are messed up. And I always rebase to achieve that. 

Anyway, earlier I already mentioned I spent time on this PR to move forward, and am not prepared to spend more than that on this lib which I am not using at all. That still is the same. I thought this would be great starting point for any rewrites, since nothing was changed on the codebase. But as it seems the work isn't acceptable, I will wish good luck and leave this topic here. Really looking forward to a working new version as soon as possible, as there are other libs which are stuck behind because of this one. Have fun, Ben and Co.! :)

**Pull request closed without merging**
