### PR TITLE
Allow Guzzle 7 too

### PR DESCRIPTION
**Pull request by GrahamCampbell**
TODO:

- [x] Update composer
- [ ] Read source code to understand Guzzle usage
- [ ] Update source code
- [ ] Confirm tests pass on both Guzzle versions

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
NB It doesn't look like the current travis config works. HHVM is testing HHVM 4 instead of 3, and there's no PHP 7.1+ runs.

**Comment by shehi** [comment]
@GrahamCampbell , travis.yml for you, if you wanna play with it:

```
language: php

before_script:
  - travis_retry composer self-update
  - travis_retry composer global require hirak/prestissimo
  - travis_retry composer install --no-interaction --prefer-source --dev
  - travis_retry phpenv rehash

script:
  - ./vendor/bin/phpcs --standard=psr2 src/
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

stages:
  - build
  
jobs:
  fast_finish: true
  include:
    - stage: build
      dist: precise
      php: 5.5
    - stage: build
      dist: precise
      php: 5.6
    - stage: build
      dist: xenial
      php: 7.0
    - stage: build
      dist: xenial
      php: 7.1
    - stage: build
      dist: xenial
      php: 7.2
    - stage: build
      dist: xenial
      php: 7.3
    - stage: build
      dist: bionic
      php: 7.4
```

**Comment by GrahamCampbell** [comment]
Given that I don't actually use this package, if anyone else want to finish off this PR, be my guest. Cherry pick my commit, and then commit the rest of the needed changes.

**Comment by shehi** [comment]
Neither do I. :) Just trying to see if we could push this through, for Guzzle-7 or not. By the looks of it, things are hopeless.

**Comment by jonnott** [comment]
@bencorlett @GrahamCampbell 

Why close this PR? The PR that has been merged doesn't provide support for Guzzle 7.x, so ????

**Pull request closed without merging**
